import { inter } from "@/config/fonts/GoogleFonts";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/config/styles/index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
